-- GENERADORES DE SECUENCIA
DROP SEQUENCE "SEQ_AUTH";
CREATE SEQUENCE "SEQ_AUTH" START WITH 2 INCREMENT BY 1 MINVALUE 2;

DROP SEQUENCE "SEQ_CURSO";
CREATE SEQUENCE "SEQ_CURSO" START WITH 7 INCREMENT BY 1 MINVALUE 7;

DROP SEQUENCE "SEQ_CURSO_USUARIO";
CREATE SEQUENCE "SEQ_CURSO_USUARIO" START WITH 1 INCREMENT BY 1 MINVALUE 1;

DROP SEQUENCE "SEQ_USUARIO";
CREATE SEQUENCE "SEQ_USUARIO" START WITH 2 INCREMENT BY 1 MINVALUE 2;

-- USUARIOS

INSERT INTO USERS (ID_USUARIO, USERNAME, PASSWORD, ENABLED, EMAIL, FECHA_ALTA) VALUES (1, 'usuario', '$2a$12$76W6G/T4HwVxAZGqOr/BM.6qlNamMrH0t5nRIk7U3DgS5zkJYLaSS', 'true', 'usuario@gmail.com', CURRENT_TIMESTAMP);


-- AUTHORITIES

INSERT INTO AUTHORITIES (ID_AUTHORITIES, USERNAME, AUTHORITY, FECHA_ALTA) VALUES (1, 'usuario', 'read', CURRENT_TIMESTAMP);
