INSERT INTO USERS (USERNAME, PASSWORD, ENABLED, EMAIL, FECHA_ALTA) VALUES ('usuario', '$2a$12$76W6G/T4HwVxAZGqOr/BM.6qlNamMrH0t5nRIk7U3DgS5zkJYLaSS', 'true', 'usuario@gmail.com', CURRENT_TIMESTAMP);

INSERT INTO AUTHORITIES (username, authority) VALUES ('usuario', 'read');

INSERT INTO CURSO (CODIGO, TITULO, DESCRIPCION, FECHA_ALTA) VALUES ('1', 'CURSO 1', 'Descripcion curso 1', CURRENT_TIMESTAMP);

INSERT INTO CURSO (CODIGO, TITULO, DESCRIPCION, FECHA_ALTA) VALUES ('2', 'CURSO 2', 'Descripcion curso 2', CURRENT_TIMESTAMP);

INSERT INTO CURSO (CODIGO, TITULO, DESCRIPCION, FECHA_ALTA) VALUES ('3', 'CURSO 3', 'Descripcion curso 3', CURRENT_TIMESTAMP);

INSERT INTO CURSO (CODIGO, TITULO, DESCRIPCION, FECHA_ALTA) VALUES ('4', 'CURSO 4', 'Descripcion curso 4', CURRENT_TIMESTAMP);

INSERT INTO CURSO (CODIGO, TITULO, DESCRIPCION, FECHA_ALTA) VALUES ('5', 'CURSO 5', 'Descripcion curso 5', CURRENT_TIMESTAMP);

INSERT INTO CURSO (CODIGO, TITULO, DESCRIPCION, FECHA_ALTA) VALUES ('6', 'CURSO 6', 'Descripcion curso 6', CURRENT_TIMESTAMP);