DROP TABLE USERS;

CREATE TABLE IF NOT EXISTS USERS (USERNAME VARCHAR(50) PRIMARY KEY, PASSWORD TEXT, ENABLED VARCHAR(50));

DROP TABLE AUTHORITIES;

CREATE TABLE IF NOT EXISTS AUTHORITIES (ID SERIAL PRIMARY KEY, USERNAME VARCHAR(50), AUTHORITY VARCHAR(50));